### ISSUE TITLE
Unable to install either the package through apt or through appimage.

### ISSUE THREAD

**Issue by bdaniel230** [patrikx3/onenote#122]
This is the error string when I try to run AppImage.  I have tried to run apt-purge P3X-OneNote but it fails to find a local installation and when I run ./P3X-OneNote I get the following:
./P3X-OneNote-2020.10.178.AppImage 
Checking for update
Generated new staging user ID: d162bd80-8a64-54b3-936e-190ead8a58ab
Error: Error: net::ERR_CONNECTION_TIMED_OUT
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:101:6400)
    at SimpleURLLoaderWrapper.emit (events.js:310:20)
Error: net::ERR_CONNECTION_TIMED_OUT
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:101:6400)
    at SimpleURLLoaderWrapper.emit (events.js:310:20)
(node:3246) UnhandledPromiseRejectionWarning: Error: net::ERR_CONNECTION_TIMED_OUT
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:101:6400)
    at SimpleURLLoaderWrapper.emit (events.js:310:20)
(node:3246) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:3246) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

[One Note Start Screen.docx](https://github.com/patrikx3/onenote/files/5525540/One.Note.Start.Screen.docx)

**Comment by bdaniel230** [comment]
Yep that was the first attempt.  All of them end up with the same result.  Even Node.js  I would bet it is a network security issue.  I am working within a large multinational and I use OneNote for my test notes but I work with Linux so I have had to write my notes out longhand then transfer them to OneNote.  I was hoping to get this working on that Ubuntu 18.04 box.
Thanks for your help though.

Daniel Beck
230 Saint Charles Court
Middleton, Idaho
83644-5495
(208) 585-3407

43.7085409 North -116.605014999 West


________________________________
