### ISSUE TITLE
Application Fails to load with Electron 14.0.1

### ISSUE THREAD

**Issue by remanifest** [patrikx3/onenote#155]
Running Arch Linux with Electron 14.0.1, and p3x-onenote fails to open, providing the below dialog:
`Uncaught Exception:
Error: @electron/remote >= 2.x is required for Electron >= 14. See https://github.com/electron/remote/blob/main/docs/migration-2.md for migration instructions.
   at Object.initialize (/usr/lib/p3x-onenote/node_modules/@electron/rmote/dist/src/main/server.js:342:15)
   at App.createWindow (usr/lib/p3x-onenote/src/electron/main/create/window/onenotejs:22:38)
   at App.emit (events.js:376:20)`

In addition, launching the program from the terminal results in the following output:
`electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(Use `electron --trace-warnings ...` to show where the warning was created)`

**Comment by remanifest** [comment]
Installed from the Arch User Repository, which uses the 2021.10.111 release's source tarball.
