### ISSUE TITLE
Error after installing

### ISSUE THREAD

**Issue by RayBB** [patrikx3/onenote#7]
Hello,
After running the install command, rebooting, and starting the app I'm getting this error.

Any idea how to fix it?
I'm running the latest version of Linux Mint.

```
p3x-onenote
/bin/sh: 1: /usr/lib/node_modules/p3x-onenote/bin/../node_modules/.bin/electron: not found

9/9/2017, 1:28:15 PM unhandledRejection { Error: Command failed: /usr/lib/node_modules/p3x-onenote/bin/../node_modules/.bin/electron /usr/lib/node_modules/p3x-onenote/bin/../src/electron/app.js
/bin/sh: 1: /usr/lib/node_modules/p3x-onenote/bin/../node_modules/.bin/electron: not found

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)
  killed: false,
  code: 127,
  signal: null,
  cmd: '/usr/lib/node_modules/p3x-onenote/bin/../node_modules/.bin/electron /usr/lib/node_modules/p3x-onenote/bin/../src/electron/app.js' } Promise {
  <rejected> { Error: Command failed: /usr/lib/node_modules/p3x-onenote/bin/../node_modules/.bin/electron /usr/lib/node_modules/p3x-onenote/bin/../src/electron/app.js
/bin/sh: 1: /usr/lib/node_modules/p3x-onenote/bin/../node_modules/.bin/electron: not found

    at ChildProcess.exithandler (child_process.js:205:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)
  killed: false,
  code: 127,
  signal: null,
  cmd: '/usr/lib/node_modules/p3x-onenote/bin/../node_modules/.bin/electron /usr/lib/node_modules/p3x-onenote/bin/../src/electron/app.js' } }

```

**Comment by RayBB** [comment]
I ran that command initially but it didn't work after restarting.
I just ran the command again and now it's working.

PS: I'm on version 7.10.1

**Comment by passer-by2017** [comment]
Hi. I met with the same problem. 
"sudo npm install -g p3x-onenote --unsafe-perm=true --allow-root" doesn't help. 
Node 8.7.0.
Any idea?

**Comment by passer-by2017** [comment]
Thank you very much. Re-installing has helped. But now I've got 
"The Microsoft account login server has detected too many repeated authentication attempts. Please wait a moment and try again". :(
